import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Share2 } from "lucide-react";
import { demoRaffles, getDemoRaffle, money, date } from "@/lib/demo";
import NumberPicker from "@/components/number-picker";

export function generateStaticParams() { return demoRaffles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const raffle = getDemoRaffle(slug); if (!raffle) return {}; return { title: `${raffle.title} | Rifly`, description: `Participa en la rifa de ${raffle.prize_name}. Elige tus números desde ${money(raffle.price_per_number)} y reserva fácilmente por WhatsApp.`, alternates: { canonical: `/rifa/${raffle.slug}` }, openGraph: { title: `${raffle.title} | Rifly`, description: raffle.description, url: `/rifa/${raffle.slug}`, type: "website", images: [{ url: "/logo.svg", width: 1200, height: 630 }] }, robots: raffle.status === "active" ? { index: true, follow: true } : { index: false, follow: false } }; }

export default async function RafflePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const raffle = getDemoRaffle(slug); if (!raffle) notFound();
  const numbers = Array.from({ length: raffle.number_end - raffle.number_start + 1 }, (_, index) => index + raffle.number_start);
  return <main className="min-h-screen bg-[#f7f8fc] px-5 py-6 md:px-10"><header className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/rifas" className="sans flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft className="h-4 w-4" /> Todas las rifas</Link><Link href="/" className="sans text-xl font-black tracking-[-.06em] text-slate-900">RIFLY</Link><button className="sans rounded-full border border-slate-200 bg-white p-2.5 text-slate-600" aria-label="Compartir rifa"><Share2 className="h-4 w-4" /></button></header><section className="mx-auto max-w-6xl pb-20 pt-10"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="flex min-h-[360px] items-end rounded-[2rem] p-8 md:min-h-[500px] md:p-12" style={{ background: raffle.accent }}><span className="text-[10rem] font-black leading-none tracking-[-.14em] md:text-[14rem]">{raffle.mark}</span></div><div className="flex flex-col justify-center"><span className="sans w-fit rounded-full bg-[#dff8ed] px-3 py-1 text-xs font-bold text-emerald-700">Rifa activa</span><h1 className="mt-5 text-6xl font-bold leading-[.92] tracking-[-.08em] md:text-8xl">{raffle.title}</h1><p className="sans mt-6 max-w-xl text-lg leading-8 text-slate-500">{raffle.description}</p><div className="mt-8 grid max-w-md grid-cols-2 gap-4 sans"><div className="rounded-2xl border border-slate-200 bg-white p-4"><span className="block text-xs text-slate-400">Por número</span><strong className="text-xl">{money(raffle.price_per_number)}</strong></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><span className="block text-xs text-slate-400">Sorteo</span><strong className="text-sm">{date(raffle.draw_at)}</strong></div></div></div></div><div className="mt-16 grid gap-8 lg:grid-cols-[1fr_280px]"><div><h2 className="text-4xl font-bold tracking-[-.06em]">Elige tus números</h2><p className="sans mt-2 text-sm text-slate-500">Los números pendientes se liberan automáticamente después de 15 minutos.</p><NumberPicker numbers={numbers} price={raffle.price_per_number} raffleTitle={raffle.title} /></div><aside className="h-fit rounded-3xl border border-slate-200 bg-white p-6 sans"><h3 className="font-bold">Estado de la rifa</h3><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[67%] rounded-full bg-[#6d4aff]" /></div><p className="mt-3 text-sm text-slate-500"><strong className="text-slate-900">67%</strong> vendido</p><div className="mt-6 space-y-3 border-t border-slate-100 pt-5 text-sm"><p className="flex justify-between"><span className="text-slate-500">Disponibles</span><strong>33</strong></p><p className="flex justify-between"><span className="text-slate-500">Premio</span><strong>{raffle.prize_name}</strong></p></div></aside></div></section></main>;
}