import Link from "next/link";
import { ArrowUpRight, ChevronRight, Sparkles } from "lucide-react";

const raffles = [
  { slug: "iphone-16-pro", title: "iPhone 16 Pro", prize: "iPhone 16 Pro 256 GB", price: 10000, sold: 67, date: "7 oct 2026", accent: "#dfe3ff", mark: "16" },
  { slug: "playstation-5", title: "PlayStation 5", prize: "PS5 Slim + 2 controles", price: 5000, sold: 42, date: "18 oct 2026", accent: "#dff8ed", mark: "PS" },
  { slug: "millon-en-efectivo", title: "$1.000.000", prize: "Un millón de pesos", price: 10000, sold: 81, date: "31 oct 2026", accent: "#fff0d7", mark: "$" },
];
const money = (value: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(value);

export default function Home() {
  return <main className="grain min-h-screen">
    <header className="sans mx-auto flex max-w-6xl items-center justify-between px-5 py-5 md:px-8">
      <Link href="/" className="flex items-center gap-2 text-xl font-black tracking-[-0.06em]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#6d4aff] text-lg text-white shadow-[0_6px_18px_#6d4aff55]">R</span>RIFLY</Link>
      <nav className="hidden items-center gap-8 text-sm font-semibold text-slate-500 md:flex"><Link href="/rifas" className="hover:text-slate-950">Rifas</Link><a href="#como-funciona" className="hover:text-slate-950">Cómo funciona</a></nav>
      <Link href="/rifas" className="sans rounded-full bg-[#101828] px-4 py-2.5 text-sm font-bold text-white transition hover:bg-[#6d4aff]">Ver rifas <ArrowUpRight className="ml-1 inline h-4 w-4" /></Link>
    </header>
    <section className="mx-auto grid max-w-6xl gap-10 px-5 pb-20 pt-12 md:grid-cols-[1.08fr_.92fr] md:items-center md:px-8 md:pt-20">
      <div><div className="sans mb-5 inline-flex items-center gap-2 rounded-full border border-[#dcd8ff] bg-white/80 px-3 py-1.5 text-xs font-bold uppercase tracking-[.14em] text-[#6d4aff]"><Sparkles className="h-3.5 w-3.5" /> rifas simples, premios reales</div><h1 className="max-w-3xl text-6xl font-bold leading-[.94] tracking-[-.075em] md:text-8xl">Tu próximo premio puede estar a <em className="font-normal text-[#6d4aff]">un número</em> de distancia.</h1><p className="sans mt-7 max-w-lg text-lg leading-8 text-slate-500">Elige tus números, reserva en segundos y confirma por WhatsApp. Sin cuentas, sin vueltas.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/rifas" className="sans rounded-full bg-[#6d4aff] px-6 py-3.5 text-sm font-bold text-white shadow-[0_10px_24px_#6d4aff45] transition hover:-translate-y-0.5">Ver rifas disponibles <ArrowUpRight className="ml-1 inline h-4 w-4" /></Link><a href="#como-funciona" className="sans rounded-full border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-700">Cómo funciona</a></div></div>
      <div className="relative min-h-[330px] rounded-[2rem] bg-[#101828] p-6 text-white shadow-2xl md:min-h-[440px] md:p-9"><div className="absolute right-6 top-6 rounded-full bg-white/10 px-3 py-1.5 sans text-xs font-bold">RIFLY / 01</div><div className="flex h-full flex-col justify-between"><div className="mt-16"><p className="sans text-xs font-bold uppercase tracking-[.18em] text-[#bdb3ff]">premio destacado</p><h2 className="mt-3 text-5xl leading-[.9] tracking-[-.07em] md:text-7xl">iPhone<br /><span className="text-[#bdb3ff]">16 Pro.</span></h2></div><div className="sans flex items-end justify-between"><div><p className="text-xs text-slate-400">Desde</p><p className="text-xl font-bold">$10.000 <span className="text-xs font-normal text-slate-400">/ número</span></p></div><Link href="/rifa/iphone-16-pro" className="grid h-12 w-12 place-items-center rounded-full bg-[#6d4aff] transition hover:scale-105"><ArrowUpRight /></Link></div></div><div className="absolute -bottom-5 -left-4 grid h-20 w-20 rotate-[-8deg] place-items-center rounded-2xl bg-[#f5c04e] text-3xl font-black text-[#101828] shadow-xl">16</div></div>
    </section>
    <section className="mx-auto max-w-6xl px-5 pb-24 md:px-8"><div className="mb-7 flex items-end justify-between"><div><p className="sans text-xs font-bold uppercase tracking-[.18em] text-[#6d4aff]">selección actual</p><h2 className="mt-2 text-4xl font-bold tracking-[-.06em]">Rifas disponibles</h2></div><Link href="/rifas" className="sans hidden items-center gap-1 text-sm font-bold text-slate-500 hover:text-[#6d4aff] sm:flex">Ver todas <ChevronRight className="h-4 w-4" /></Link></div><div className="grid gap-4 md:grid-cols-3">{raffles.map((raffle) => <Link href={`/rifa/${raffle.slug}`} key={raffle.slug} className="group overflow-hidden rounded-3xl border border-slate-200/80 bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative grid h-52 place-items-center" style={{ background: raffle.accent }}><span className="text-8xl font-black tracking-[-.12em] text-[#101828] opacity-80">{raffle.mark}</span><span className="absolute left-4 top-4 rounded-full bg-white/75 px-3 py-1 sans text-xs font-bold text-slate-600">{raffle.sold}% vendido</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-2xl font-bold tracking-[-.05em]">{raffle.title}</h3><p className="sans mt-1 text-sm text-slate-500">{raffle.prize}</p></div><ArrowUpRight className="h-5 w-5 text-slate-300 transition group-hover:text-[#6d4aff]" /></div><div className="mt-5 flex items-end justify-between border-t border-slate-100 pt-4 sans"><div><p className="text-xs text-slate-400">Por número</p><p className="font-bold">{money(raffle.price)}</p></div><p className="text-right text-xs text-slate-400">Sorteo<br /><strong className="text-slate-700">{raffle.date}</strong></p></div></div></Link>)}</div></section>
    <section id="como-funciona" className="border-y border-slate-200 bg-white/70"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 md:grid-cols-3 md:px-8">{[["01", "Elige", "Encuentra un premio que te emocione y revisa los números disponibles."], ["02", "Reserva", "Selecciona uno o varios números. Solo te pediremos nombre y WhatsApp."], ["03", "Confirma", "Recibe tu código y continúa por WhatsApp para completar el proceso."]].map(([num, title, text]) => <div key={num}><span className="sans text-sm font-bold text-[#6d4aff]">{num}</span><h3 className="mt-4 text-3xl font-bold tracking-[-.05em]">{title}</h3><p className="sans mt-2 leading-7 text-slate-500">{text}</p></div>)}</div></section>
    <footer className="sans mx-auto flex max-w-6xl flex-col gap-3 px-5 py-8 text-sm text-slate-400 md:flex-row md:items-center md:justify-between md:px-8"><span className="font-bold tracking-[-.04em] text-slate-700">RIFLY</span><span>Rifas claras. Premios que importan.</span><span>© 2026 Rifly</span></footer>
  </main>;
}
