"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { money } from "@/lib/format";

export default function NumberPicker({ raffleId, numbers, price, raffleTitle, raffleSlug }: { raffleId: string; numbers: { number: number; status: string }[]; price: number; raffleTitle: string; raffleSlug: string }) {
  const [selected, setSelected] = useState<number[]>([]);
  const toggle = (number: number) => setSelected((current) => current.includes(number) ? current.filter((item) => item !== number) : [...current, number]);
  return <div className="mt-8"><div className="mb-6 flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#6d4aff] sans text-sm font-bold text-white">1</span><div><p className="sans text-xs font-bold uppercase tracking-[.14em] text-[#6d4aff]">Paso 1 de 2</p><p className="sans text-sm font-semibold text-slate-700">Elige uno o varios números</p></div></div><div className="mb-5 flex flex-wrap gap-4 sans text-xs font-semibold text-slate-500"><span><i className="mr-1 inline-block h-3 w-3 rounded bg-white ring-1 ring-slate-200" /> Disponible</span><span><i className="mr-1 inline-block h-3 w-3 rounded bg-[#6d4aff]" /> Seleccionado</span><span><i className="mr-1 inline-block h-3 w-3 rounded bg-[#fef0c7]" /> Pendiente</span></div><div className="grid grid-cols-5 gap-2 sm:grid-cols-10">{numbers.map(({ number, status }) => { const unavailable = status !== "available"; return <button type="button" key={number} disabled={unavailable} onClick={() => toggle(number)} aria-label={`Número ${number}: ${status}`} aria-pressed={selected.includes(number)} className={`aspect-square rounded-xl border text-sm font-bold transition ${selected.includes(number) ? "border-[#6d4aff] bg-[#6d4aff] text-white shadow-lg shadow-[#6d4aff44]" : unavailable ? status === "pending" ? "cursor-not-allowed border-amber-200 bg-[#fef0c7] text-amber-800" : "cursor-not-allowed border-slate-200 bg-slate-100 text-slate-400" : "border-slate-200 bg-white text-slate-600 hover:border-[#6d4aff] hover:text-[#6d4aff]"}`}>{String(number).padStart(numbers.length > 100 ? 3 : 2, "0")}</button>; })}</div>{selected.length > 0 && <div className="sticky bottom-4 mt-8 flex items-center justify-between gap-4 rounded-2xl bg-[#101828] p-4 text-white shadow-2xl sans"><div><p className="text-xs text-slate-400">{selected.length} {selected.length === 1 ? "número" : "números"} seleccionados</p><strong>{money(selected.length * price)}</strong></div><Link href={`/reserva/nueva?numbers=${selected.join(",")}&raffle=${encodeURIComponent(raffleTitle)}&raffleId=${raffleId}&slug=${raffleSlug}`} className="rounded-xl bg-[#6d4aff] px-4 py-3 text-sm font-bold">Continuar <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div>}</div>;
}