"use client";
/* eslint-disable @next/next/no-img-element */
import { useState } from "react";
import { ImagePlus, Save, Upload } from "lucide-react";
import { useRouter } from "next/navigation";
import DateTimePicker from "@/components/date-time-picker";
import NumericField from "@/components/numeric-field";
import PhoneField from "@/components/phone-field";

type Raffle = { id: string; title: string; slug: string; description: string; prize_name: string; price_per_number: number; sales_close_at: string; draw_at: string; draw_method: string; whatsapp_number: string | null; payment_instructions: string | null; reservation_minutes: number; status: string; image_path: string | null };
const localDate = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
const imageUrl = (path: string | null) => path ? `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/raffles/${path}` : null;

export default function RaffleEditForm({ raffle }: { raffle: Raffle }) {
  const router = useRouter(); const [price, setPrice] = useState(String(raffle.price_per_number)); const [minutes, setMinutes] = useState(String(raffle.reservation_minutes)); const [closeAt, setCloseAt] = useState(localDate(raffle.sales_close_at)); const [drawAt, setDrawAt] = useState(localDate(raffle.draw_at)); const [phone, setPhone] = useState(raffle.whatsapp_number ?? ""); const [preview, setPreview] = useState(imageUrl(raffle.image_path)); const [image, setImage] = useState<File | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  function selectImage(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 5 * 1024 * 1024) return setError("Usa JPG, PNG o WebP de máximo 5 MB."); setError(""); setImage(file); setPreview(URL.createObjectURL(file)); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); form.set("pricePerNumber", price); form.set("reservationMinutes", minutes); form.set("salesCloseAt", closeAt); form.set("drawAt", drawAt); form.set("whatsappNumber", phone); if (image) form.set("image", image); const response = await fetch(`/api/admin/raffles/${raffle.id}`, { method: "PATCH", body: form }); const result = await response.json(); setLoading(false); if (!response.ok) return setError(result.error ?? "No se pudo actualizar la rifa."); router.push(`/admin/rifas/${raffle.id}`); }
  return <form onSubmit={submit} className="space-y-7"><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Nombre de la rifa" defaultValue={raffle.title} /><TextField name="slug" label="Slug" defaultValue={raffle.slug} /><TextField name="prizeName" label="Nombre del premio" defaultValue={raffle.prize_name} /><NumericField name="pricePerNumber" label="Precio por número" value={price} onChange={setPrice} min={1} /><DateTimePicker name="salesCloseAt" label="Cierre de ventas" value={closeAt} onChange={setCloseAt} /><DateTimePicker name="drawAt" label="Fecha del sorteo" value={drawAt} onChange={setDrawAt} /><TextField name="drawMethod" label="Método del sorteo" defaultValue={raffle.draw_method} /><NumericField name="reservationMinutes" label="Minutos de reserva" value={minutes} onChange={setMinutes} min={1} max={1440} /></div><label className="block sans text-sm font-bold">Descripción<textarea name="description" required minLength={10} defaultValue={raffle.description} rows={5} className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#6d4aff]" /></label><div className="grid gap-5 md:grid-cols-2"><PhoneField name="whatsappNumber" label="WhatsApp de la rifa" value={phone} onChange={setPhone} /><TextField name="paymentInstructions" label="Instrucciones de pago" defaultValue={raffle.payment_instructions ?? ""} required={false} /></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="flex items-center gap-2"><ImagePlus className="h-5 w-5 text-[#6d4aff]" /><h2 className="sans text-sm font-bold">Portada</h2></div>{preview ? <img src={preview} alt="Portada" className="mt-4 h-56 w-full rounded-xl object-cover" /> : <div className="mt-4 grid h-40 place-items-center rounded-xl bg-[#eeeaff] text-[#6d4aff]">Sin portada</div>}<label htmlFor="edit-image" className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 sans text-sm font-bold"><Upload className="h-4 w-4" /> Reemplazar portada<input id="edit-image" type="file" accept="image/jpeg,image/png,image/webp" onChange={selectImage} className="sr-only" /></label></div><select name="status" defaultValue={raffle.status} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 sans text-sm"><option value="draft">Borrador</option><option value="active">Activa</option><option value="closed">Cerrada</option><option value="finished">Finalizada</option></select>{error && <p className="rounded-xl bg-red-50 p-4 sans text-sm text-red-700">{error}</p>}<button disabled={loading} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#6d4aff] px-5 py-3.5 sans text-sm font-bold text-white disabled:opacity-50"><Save className="h-4 w-4" />{loading ? "Guardando..." : "Guardar cambios"}</button><p className="sans text-xs text-slate-400">El rango de números no se modifica aquí para proteger reservas existentes.</p></form>;
}
function TextField({ name, label, defaultValue, required = true }: { name: string; label: string; defaultValue: string; required?: boolean }) { return <label className="block sans text-sm font-bold">{label}<input name={name} required={required} defaultValue={defaultValue} className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#6d4aff]" /></label>; }
