"use client";
import Link from "@/components/loading-link";
import LoadingButton from "@/components/loading-button";
/* eslint-disable @next/next/no-img-element */
import { useState, useTransition } from "react";
import { ArrowLeft, ArrowRight, Check, Gift, ImagePlus, Info, Ticket, Upload, X } from "lucide-react";
import { useRouter } from "next/navigation";
import PhoneField from "@/components/phone-field";
import DateTimePicker from "@/components/date-time-picker";
import NumericField from "@/components/numeric-field";
import { money } from "@/lib/format";

const steps = ["Datos básicos", "Fechas y dinámica", "Portada y contacto", "Revisar y publicar"];
const slugify = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
type ImageState = { file: File; url: string } | null;

type FieldProps = { name: string; label: string; type?: string; placeholder?: string; defaultValue?: string; min?: string; max?: string; value?: string; onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void };

export default function RaffleCreateForm() {
  const router = useRouter(); const [navigating, startNavigation] = useTransition();
  const [step, setStep] = useState(0); const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [prize, setPrize] = useState(""); const [price, setPrice] = useState(""); const [numberStart, setNumberStart] = useState("0"); const [numberEnd, setNumberEnd] = useState("99"); const [reservationMinutes, setReservationMinutes] = useState("15"); const [drawMethod, setDrawMethod] = useState("Lotería"); const [salesCloseAt, setSalesCloseAt] = useState(""); const [drawAt, setDrawAt] = useState(""); const [image, setImage] = useState<ImageState>(null); const [slugEdited, setSlugEdited] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const progress = ((step + 1) / 4) * 100;

  function selectImage(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) return setError("Selecciona JPG, PNG o WebP."); if (file.size > 5 * 1024 * 1024) return setError("La portada no puede superar 5 MB."); if (image) URL.revokeObjectURL(image.url); setError(""); setImage({ file, url: URL.createObjectURL(file) }); }
  function nextStep() { setError(""); if (step === 0 && (!title.trim() || !prize.trim() || !price)) return setError("Completa nombre, premio y precio."); if (step === 1 && (!salesCloseAt || !drawAt || Number(numberEnd) < Number(numberStart))) return setError("Completa fechas y revisa el rango de números."); if (step === 2 && !image) return setError("Selecciona una portada para continuar."); setStep((current) => Math.min(current + 1, 3)); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (loading || navigating) return; try { if (!image) return setError("Selecciona una portada para la rifa."); setLoading(true); setError(""); const formData = new FormData(event.currentTarget); formData.set("image", image.file); const response = await fetch("/api/admin/raffles", { method: "POST", body: formData }); const result = await response.json(); if (!response.ok) return setError(result.error ?? "No se pudo crear la rifa."); startNavigation(() => router.push(`/admin/rifas/${result.id}`)); } catch { setError("No pudimos conectar. Intenta nuevamente."); } finally { setLoading(false); } }

  return <form onSubmit={submit} className="rounded-[22px] border border-slate-200 bg-white shadow-sm">
    <header className="border-b border-slate-100 px-5 py-5 md:px-8"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eeeaff] text-[#6d4aff]"><Gift className="h-5 w-5" /></span><div><h1 className="text-xl font-bold tracking-[-.04em] md:text-2xl">Crear nueva rifa</h1><p className="mt-1 sans text-xs text-slate-500">Configura tu rifa paso a paso</p></div></div><Link href="/admin" className="hidden items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 sans text-xs font-bold text-slate-600 sm:flex"><ArrowLeft className="h-3.5 w-3.5" /> Volver</Link></div><div className="mt-7 grid grid-cols-4 gap-2 md:gap-5">{steps.map((label, index) => <button type="button" disabled={loading || navigating} key={label} onClick={() => index <= step && setStep(index)} className="text-left"><div className="flex items-center gap-2"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full sans text-sm font-bold ${index < step ? "bg-emerald-500 text-white" : index === step ? "bg-[#6d4aff] text-white" : "bg-slate-100 text-slate-500"}`}>{index < step ? <Check className="h-4 w-4" /> : index + 1}</span><span className={`hidden sans text-xs font-bold lg:block ${index === step ? "text-[#5a38e8]" : "text-slate-600"}`}>{label}</span></div></button>)}</div></header>
    <div className="grid lg:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 p-5 md:p-8">
      <section className={step === 0 ? "block" : "hidden"}><StepHeading title="Paso 1. Datos básicos" text="Define el nombre de tu rifa, el premio y el precio por número." /><div className="grid gap-5 md:grid-cols-2"><Field name="title" label="Nombre de la rifa" placeholder="Ej. iPhone 16 Pro" value={title} onChange={(event) => { setTitle(event.target.value); if (!slugEdited) setSlug(slugify(event.target.value)); }} /><Field name="slug" label="Slug de la URL" value={slug} onChange={(event) => { setSlugEdited(true); setSlug(slugify(event.target.value)); }} /><Field name="prizeName" label="Nombre del premio" placeholder="iPhone 16 Pro 256 GB" value={prize} onChange={(event) => setPrize(event.target.value)} /><NumericField name="pricePerNumber" label="Precio por número" value={price} onChange={setPrice} placeholder="10.000" min={1} /></div></section>
      <section className={step === 1 ? "block" : "hidden"}><StepHeading title="Paso 2. Fechas y dinámica" text="Define el rango, el cierre y cómo se realizará el sorteo." /><div className="grid gap-5 md:grid-cols-2"><NumericField name="numberStart" label="Número inicial" value={numberStart} onChange={setNumberStart} min={0} /><NumericField name="numberEnd" label="Número final" value={numberEnd} onChange={setNumberEnd} min={Number(numberStart) || 0} /><DateTimePicker name="salesCloseAt" label="Cierre de ventas" value={salesCloseAt} onChange={setSalesCloseAt} /><DateTimePicker name="drawAt" label="Fecha del sorteo" value={drawAt} onChange={setDrawAt} /><Field name="drawMethod" label="Método del sorteo" value={drawMethod} onChange={(event) => setDrawMethod(event.target.value)} /><NumericField name="reservationMinutes" label="Minutos de reserva" value={reservationMinutes} onChange={setReservationMinutes} min={1} max={1440} /></div><label className="mt-5 block sans text-sm font-bold">Descripción<textarea name="description" required minLength={10} rows={4} className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#6d4aff]" placeholder="Describe el premio y las condiciones." /></label></section>
      <section className={step === 2 ? "block" : "hidden"}><StepHeading title="Paso 3. Portada y contacto" text="Añade la imagen del premio y los datos de confirmación." /><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="flex items-center gap-2"><ImagePlus className="h-5 w-5 text-[#6d4aff]" /><h2 className="sans text-sm font-bold">Portada de la rifa</h2></div><p className="mt-1 sans text-xs text-slate-500">JPG, PNG o WebP · máximo 5 MB</p><div className="mt-4">{image ? <div className="relative overflow-hidden rounded-xl"><img src={image.url} alt="Vista previa de portada" className="h-64 w-full object-cover" /><button type="button" onClick={() => { URL.revokeObjectURL(image.url); setImage(null); }} className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-lg bg-white text-red-600 shadow" aria-label="Quitar portada"><X className="h-4 w-4" /></button></div> : <label htmlFor="image" className="flex min-h-52 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#cfc8ff] bg-[#f5f3ff] text-center"><Upload className="h-6 w-6 text-[#6d4aff]" /><span className="mt-3 sans text-sm font-bold">Selecciona la portada del premio</span><span className="mt-1 sans text-xs text-slate-500">Haz clic para buscar una imagen</span><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" required onChange={selectImage} className="sr-only" /></label>}</div></div><div className="mt-5 grid gap-5 md:grid-cols-2"><PhoneField name="whatsappNumber" label="WhatsApp de la rifa" /><label className="block sans text-sm font-bold">Instrucciones de pago<input name="paymentInstructions" placeholder="Nequi, transferencia..." className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#6d4aff]" /></label></div></section>
      <section className={step === 3 ? "block" : "hidden"}><StepHeading title="Paso 4. Revisa y publica" text="Verifica los datos antes de guardarlos en Supabase." /><div className="divide-y divide-slate-100 rounded-2xl border border-slate-200 bg-slate-50"><Review label="Nombre" value={title || "Sin definir"} /><Review label="Premio" value={prize || "Sin definir"} /><Review label="Precio" value={price ? money(Number(price)) : "Sin definir"} /><Review label="Fechas" value={salesCloseAt && drawAt ? "Configuradas" : "Pendientes"} /><Review label="Portada" value={image?.file.name || "Sin seleccionar"} /></div><input type="hidden" name="status" value="draft" /><label className="mt-5 flex items-center gap-3 sans text-sm"><input type="checkbox" name="status" value="active" className="h-4 w-4 accent-[#6d4aff]" /> Publicar inmediatamente</label></section>
      {error && <p className="mt-6 rounded-xl bg-red-50 p-4 sans text-sm text-red-700">{error}</p>}<footer className="mt-8 flex items-center justify-between gap-3 border-t border-slate-100 pt-6"><div className="hidden items-center gap-3 sm:flex"><span className="sans text-xs font-bold text-slate-500">Paso {step + 1} de 4</span><div className="h-2 w-40 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#6d4aff]" style={{ width: `${progress}%` }} /></div><span className="sans text-xs text-slate-500">{Math.round(progress)}%</span></div><div className="flex w-full justify-between gap-3 sm:w-auto"><button type="button" onClick={() => setStep((current) => Math.max(current - 1, 0))} disabled={step === 0 || loading || navigating} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 sans text-sm font-bold text-slate-600 disabled:invisible"><ArrowLeft className="h-4 w-4" /> Atrás</button>{step < 3 ? <button type="button" onClick={nextStep} className="inline-flex items-center gap-2 rounded-xl bg-[#6d4aff] px-5 py-3 sans text-sm font-bold text-white">Continuar <ArrowRight className="h-4 w-4" /></button> : <LoadingButton loading={loading || navigating} disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-[#6d4aff] px-5 py-3 sans text-sm font-bold text-white disabled:opacity-50">{loading ? "Guardando..." : "Crear rifa"}<Check className="h-4 w-4" /></LoadingButton>}</div></footer></div><Preview title={title} prize={prize} price={price} numberStart={numberStart} numberEnd={numberEnd} drawMethod={drawMethod} image={image} /></div>
  </form>;
}

function StepHeading({ title, text }: { title: string; text: string }) { return <div className="mb-7"><p className="sans text-xs font-bold uppercase tracking-[.14em] text-[#6d4aff]">RIFLY · CONFIGURACIÓN</p><h2 className="mt-2 text-3xl font-bold tracking-[-.06em]">{title}</h2><p className="mt-2 sans text-sm leading-6 text-slate-500">{text}</p></div>; }
function Review({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 px-4 py-3 sans text-sm"><span className="text-slate-500">{label}</span><strong className="truncate text-right">{value}</strong></div>; }
function Preview({ title, prize, price, numberStart, numberEnd, drawMethod, image }: { title: string; prize: string; price: string; numberStart: string; numberEnd: string; drawMethod: string; image: ImageState }) { return <aside className="hidden border-l border-slate-100 bg-slate-50/60 p-5 lg:block"><div className="sticky top-24"><p className="text-lg font-bold">Vista previa</p><p className="mt-1 sans text-xs text-slate-500">Así se verá tu rifa.</p><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{image ? <img src={image.url} alt="Preview" className="h-40 w-full object-cover" /> : <div className="grid h-40 place-items-center bg-[#eeeaff] text-[#6d4aff]"><Ticket className="h-10 w-10" /></div>}<div className="p-4"><h3 className="truncate text-xl font-bold">{title || "Nombre de la rifa"}</h3><p className="mt-1 truncate sans text-xs text-slate-500">{prize || "Nombre del premio"}</p><div className="mt-4 space-y-3 border-t border-slate-100 pt-4 sans text-xs"><div className="flex justify-between"><span className="text-slate-500">Precio</span><strong>{price ? money(Number(price)) : "$0"}</strong></div><div className="flex justify-between"><span className="text-slate-500">Rango</span><strong>{numberStart} - {numberEnd}</strong></div><div className="flex justify-between"><span className="text-slate-500">Sorteo</span><strong>{drawMethod}</strong></div></div></div></div><div className="mt-5 flex gap-2 rounded-xl bg-[#eeeaff] p-3 text-[#5a38e8]"><Info className="h-4 w-4 shrink-0" /><p className="sans text-xs">Completa los pasos para publicar.</p></div></div></aside>; }
function Field({ name, label, type = "text", placeholder, defaultValue, min, max, value, onChange }: FieldProps) { return <label className="block sans text-sm font-bold">{label}<input name={name} required type={type} placeholder={placeholder} defaultValue={defaultValue} value={value} onChange={onChange} min={min} max={max} className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none transition focus:border-[#6d4aff] focus:ring-4 focus:ring-[#6d4aff12]" /></label>; }
