import Link from "@/components/loading-link";
import { ArrowUpRight } from "lucide-react";
import { date, getPublicRaffles, money, publicImageUrl } from "@/lib/raffles";

export const metadata = { title: "Rifas disponibles", description: "Elige una rifa, selecciona tus números y reserva por WhatsApp." };

export default async function RifasPage() {
  const raffles = await getPublicRaffles();
  return <main className="min-h-screen bg-[#f7f8fc] px-5 py-6 md:px-10"><header className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/" className="sans flex items-center gap-2 text-xl font-black tracking-[-.06em]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#6d4aff] text-white">R</span>RIFLY</Link><Link href="/" className="sans text-sm font-bold text-slate-500">Volver al inicio</Link></header><section className="mx-auto max-w-6xl pb-20 pt-16"><p className="sans text-xs font-bold uppercase tracking-[.18em] text-[#6d4aff]">elige tu oportunidad</p><h1 className="mt-3 max-w-2xl text-6xl font-bold tracking-[-.07em]">Rifas disponibles.</h1><p className="sans mt-5 max-w-xl text-lg leading-8 text-slate-500">Premios claros, números visibles y reservas que puedes confirmar desde tu celular.</p>{raffles.length === 0 ? <div className="mt-12 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><h2 className="text-3xl font-bold tracking-[-.05em]">No hay rifas activas en este momento.</h2><p className="mt-3 sans text-slate-500">Vuelve pronto para descubrir las próximas.</p></div> : <div className="mt-12 grid gap-5 md:grid-cols-3">{raffles.map((raffle) => <Link href={`/rifa/${raffle.slug}`} key={raffle.id} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="grid h-60 place-items-center bg-[#e8e5ff] bg-cover bg-center" style={publicImageUrl(raffle.image_path) ? { backgroundImage: `url(${publicImageUrl(raffle.image_path)})` } : undefined}>{!raffle.image_path && <span className="text-8xl font-black tracking-[-.12em]">{raffle.title.slice(0, 2).toUpperCase()}</span>}</div><div className="p-6"><div className="flex justify-between"><div><h2 className="text-3xl font-bold tracking-[-.06em]">{raffle.title}</h2><p className="sans mt-1 text-sm text-slate-500">{raffle.prize_name}</p></div><ArrowUpRight className="text-slate-300 group-hover:text-[#6d4aff]" /></div><div className="mt-7 flex justify-between border-t border-slate-100 pt-4 sans text-sm"><span><span className="block text-xs text-slate-400">Por número</span><strong>{money(raffle.price_per_number)}</strong></span><span className="text-right"><span className="block text-xs text-slate-400">Sorteo</span><strong>{date(raffle.draw_at)}</strong></span></div></div></Link>)}</div>}</section></main>;
}
